# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      # - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      # - id: check-xml
      - id: debug-statements
      # - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending  # force UNIX file endings for consistency
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--autofix, --indent, "2", --no-ensure-ascii, --no-sort-keys]
        exclude: |
          (?x)(
            ^Pipfile\.lock$|
            /fixtures/.*\.json$
          )
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
        args: [requirements-dev.txt]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3  # Should be a command that runs python3.6+
        exclude: .+\/migrations.*\.py$
        args: [-t, py37, -l, "119"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: .+\/migrations.*\.py$
  - repo: https://github.com/martyzz1/pre-commit-hooks
    rev: v1.8
    hooks:
      - id: prepend-branch-name
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        args: [--allow-raw]
